#!/bin/sh
# /etc/init.d/zeroecks

case "$1" in
    start)
        python zeroecks/application.py --config=zeroecks/config.py
        ;;
    stop)
        ;;
    *)
        echo "Usage: /etc/init.d/zeroecks {start|stop}"
        exit 1
        ''
esac

exit 0
