template_path = 'zeroecks/templates'
static_path = 'zeroecks/assets'
dbname = 'zeroecks'
dbuser = 'postgres'
dbpass = 'postgres'
server = 'BIMC Illuminated'
cookie_secret = 'placeholder_cookie_secret'
